package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.PasswordField;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.sql.ResultSet;
import java.sql.SQLException;

public class LoginController {
	@FXML
	private PasswordField text_2;
	@FXML
	private Button btn_2;
	@FXML
	private TextField text_1;
	@FXML
	private Button btn_1;
	public static Statement stmt;//创建statement类对象，用来执行SQL语句！	 

	// Event Listener on Button[#btn_2].onAction
	@FXML
	public void evenButton(ActionEvent event) {
		// TODO Autogenerated
		//清空输入的用户名和密码
		text_1.setText("");
		text_2.setText("");
	}
	public void initialize() {
		btn_1.setOnAction( new EventHandler<ActionEvent>() {
			@Override
			public void handle(ActionEvent event) {
				int flag = 0;
				String id = text_1.getText();
				String password = text_2.getText();
				if(id.isEmpty()&&password.isEmpty()) {
					JOptionPane.showMessageDialog(new JFrame().getContentPane(), 
	              			"请输入账号和密码！", "警告", JOptionPane.WARNING_MESSAGE);
	    			return;
				}
				else if(!id.isEmpty()&&password.isEmpty()) {
					JOptionPane.showMessageDialog(new JFrame().getContentPane(), 
	              			"请输入密码！", "警告", JOptionPane.WARNING_MESSAGE);
	    			return;
				}
				else if(id.isEmpty()&&!password.isEmpty()) {
					JOptionPane.showMessageDialog(new JFrame().getContentPane(), 
	              			"请输入账号！", "警告", JOptionPane.WARNING_MESSAGE);
	    			return;
				}
				else {
					String driver = "com.mysql.cj.jdbc.Driver";
			        // 获取mysql连接地址
			        // MySQL的JDBC URL编写方式：jdbc:mysql://主机名称：连接端口/数据库的名称?参数=值
			       String url = "jdbc:mysql://localhost:3306/storehouse?&useSSL=false&serverTimezone=UTC";
			        // 数据名称
			       String username = "root";
			        // 数据库密码
			        String sqlpassword = "123456sql";
			        // 获取一个数据的连接
			        Connection conn = null;
			        // 获取连接的一个状态
			        try {
			        	Class.forName(driver);
			            //getConnection()方法，连接MySQL数据库！
			            conn=DriverManager.getConnection(url,username,sqlpassword);
			            stmt = conn.createStatement();
			            if(!conn.isClosed())
			            	System.out.println("数据库连接成功！");
			             
			            
			            String realid = null;//登录人员的ID
			            String realname = null;//登录人员的名字
			            String realclass = null;//登录人员的级别
			            
			            String sql = null;//要执行的SQL语句
			            sql="select * from users" ;
			            //ResultSet类，用来存放获取的结果集！
			            ResultSet rs=stmt.executeQuery(sql);
			            while(rs.next()) {
			            	realid = rs.getString("userID");
			            	realname = rs.getString("username");
			            	realclass = rs.getString("clss");
			            	
			            	
			            	
		            		
			            	if(id.equals(realid)&&password.equals(rs.getString("password"))) {//密码账号正确
			            		flag = 1;
			            		text_1.setText("");
			            		text_2.setText("");//登录成功，将账号密码框输入清空
			            		System.out.println("start！");
			            		
			            		Main.Login_ID = realid;
			            		Main.Login_name = realname;
			            		Main.Login_class = realclass;
			            		System.out.println(realid + " " +realname + " " + realclass);
			            		
			            		 Parent root = null;
			            		 String string = null;
			            		if(realclass.contentEquals("2")) {
			            			root = FXMLLoader.load(getClass().getResource("/caigou.fxml"));
			            			string = " 采购人员，";
			            		}
			            		else if(realclass.contentEquals("3")) {
			            			root = FXMLLoader.load(getClass().getResource("/xiaoshou.fxml"));
			            			string = " 销售人员，";
			            		}
			            		else {
			            			root = FXMLLoader.load(getClass().getResource("/shenhe.fxml"));
			            			string = " 审核人员，";
			            		}
								//Scene scene = new Scene(root,600,350);
								Main.CurStage.setScene(new Scene(root));
								Main.CurStage.setResizable(true);
								Main.CurStage.setTitle(realname+string+"-欢迎您！");
								Main.CurStage.show();
			            		break;
			            		
			            	}
			            }
			            if(flag == 0) {//没有找到对应的账号密码
			            	text_2.setText("");
			            	JOptionPane.showMessageDialog(new JFrame().getContentPane(), 
			              			"账号或密码不正确！", "警告", JOptionPane.WARNING_MESSAGE);
			    			return;
			            }
			        }
			        catch(ClassNotFoundException e) {
			        	//数据库驱动类异常处理
			            System.out.println("数据库驱动加载失败！");
			            e.printStackTrace();
			        }
			        catch(SQLException e1){
			            //数据库连接失败异常处理
			             e1.printStackTrace();
			        }
			        catch(Exception e2){
			            e2.printStackTrace();
			        }
				}
				
			}
		});
	}
}
